### ISSUE TITLE
Add gitchangelog

### ISSUE THREAD

**Issue by dutradda** [dutradda/jsondaora#1]
Info:
https://pypi.org/project/gitchangelog/

Acceptance Criteria:
- Just use the default configurations, It is OK.

**Comment by pniedzwiedzinski** [comment]
I would like to do this.

When you want this changelog to be generated? [This](https://pre-commit.com/) sounds ok, but every contributor will have to have it installed.

**Comment by dutradda** [comment]
@pniedzwiedzinski 
Thank you for your interest!

But I decided to not use this tool, I have been created a simple shell script that do this job.

I will close this issue, but I will create more issues for the jsondaora lib, you can get other issue to contribute!
