### ISSUE TITLE
Supporting nesting standard types

### ISSUE THREAD

**Issue by asduj** [dutradda/jsondaora#14]
Hello!
Do you have any plan to support standard types like this:

```
class Token(TypedDict):
    roles: Dict[str, List[int]]
```

**Comment by dutradda** [comment]
hello @asduj !
Thank you for open the issue!

I have implemented the deserialization for the following types: Dict, List, Tuple, Set, Union and Any.

It is on the new version [0.10.0](https://pypi.org/project/jsondaora/0.10.0/)
